### ISSUE TITLE
Problem with site

### ISSUE THREAD

**Issue by OneBobone** [delight-im/exportify#1]
The site https://rawgit.com/delight-im/exportify/master/exportify.html
does not work.
You appear to login, but no playlists are displayed.

**Comment by ocram** [comment]
Thank you!

This should have been fixed in https://github.com/delight-im/exportify/commit/06f13da01aab6f417a150116bca808df634f8d98 now.

Please let us know if that works.

**Comment by bjohas** [comment]
Thank you for fixing this!!

**Comment by ocram** [comment]
@bjohas Thanks, glad to hear that it works!
