### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI (closed)

### ISSUE THREAD

**Issue by bjohas** [delight-im/exportify#2]
Hello,

I'm trying to run the code with my own client_id to avoid rate limiting.

However, when I try to run the code myself (from a public IP or a local IP, with your or my client id) or when I try to run it from your raw git with client_id=(my id), I get a "INVALID_CLIENT: Invalid redirect URI".

What does that mean?

THANKS!

**Comment by bjohas** [comment]
Apologies! Answer: In the settings for your Spotify app (described by client_id) make sure you set a callback url. I.e. for using the raw git code, the raw git url needs to be added under settings.

**Comment by ocram** [comment]
No problem!

That’s indeed documented in the README – but further down, so it can be easily overlooked.

**Comment by bjohas** [comment]
@ocram  Ha - serves me well for not reading it properly :)
